// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/connector/tracedurationconnector/internal/metadata"

	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.ConnectorGroupbytraceConfNumTraces.Record(context.Background(), 1)
	tb.ConnectorGroupbytraceEventLatency.Record(context.Background(), 1)
	tb.ConnectorGroupbytraceIncompleteReleases.Add(context.Background(), 1)
	tb.ConnectorGroupbytraceNumEventsInQueue.Record(context.Background(), 1)
	tb.ConnectorGroupbytraceNumTracesInMemory.Record(context.Background(), 1)
	tb.ConnectorGroupbytraceSpansReleased.Add(context.Background(), 1)
	tb.ConnectorGroupbytraceTracesEvicted.Add(context.Background(), 1)
	tb.ConnectorGroupbytraceTracesReleased.Add(context.Background(), 1)
	AssertEqualConnectorGroupbytraceConfNumTraces(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualConnectorGroupbytraceEventLatency(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualConnectorGroupbytraceIncompleteReleases(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualConnectorGroupbytraceNumEventsInQueue(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualConnectorGroupbytraceNumTracesInMemory(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualConnectorGroupbytraceSpansReleased(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualConnectorGroupbytraceTracesEvicted(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualConnectorGroupbytraceTracesReleased(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
