// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := SetupTelemetry()
	tb, err := metadata.NewTelemetryBuilder(
		testTel.NewTelemetrySettings(),
	)
	require.NoError(t, err)
	require.NotNil(t, tb)
	tb.ConnectorGroupbytraceConfNumTraces.Record(context.Background(), 1)
	tb.ConnectorGroupbytraceEventLatency.Record(context.Background(), 1)
	tb.ConnectorGroupbytraceIncompleteReleases.Add(context.Background(), 1)
	tb.ConnectorGroupbytraceNumEventsInQueue.Record(context.Background(), 1)
	tb.ConnectorGroupbytraceNumTracesInMemory.Record(context.Background(), 1)
	tb.ConnectorGroupbytraceSpansReleased.Add(context.Background(), 1)
	tb.ConnectorGroupbytraceTracesEvicted.Add(context.Background(), 1)
	tb.ConnectorGroupbytraceTracesReleased.Add(context.Background(), 1)

	testTel.AssertMetrics(t, []metricdata.Metrics{
		{
			Name:        "otelcol_connector_groupbytrace_conf_num_traces",
			Description: "Maximum number of traces to hold in the internal storage",
			Unit:        "1",
			Data: metricdata.Gauge[int64]{
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_connector_groupbytrace_event_latency",
			Description: "How long the queue events are taking to be processed",
			Unit:        "ms",
			Data: metricdata.Histogram[int64]{
				Temporality: metricdata.CumulativeTemporality,
				DataPoints: []metricdata.HistogramDataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_connector_groupbytrace_incomplete_releases",
			Description: "Releases that are suspected to have been incomplete",
			Unit:        "1",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_connector_groupbytrace_num_events_in_queue",
			Description: "Number of events currently in the queue",
			Unit:        "1",
			Data: metricdata.Gauge[int64]{
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_connector_groupbytrace_num_traces_in_memory",
			Description: "Number of traces currently in the in-memory storage",
			Unit:        "1",
			Data: metricdata.Gauge[int64]{
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_connector_groupbytrace_spans_released",
			Description: "Spans released to the next consumer",
			Unit:        "1",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_connector_groupbytrace_traces_evicted",
			Description: "Traces evicted from the internal buffer",
			Unit:        "1",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_connector_groupbytrace_traces_released",
			Description: "Traces released to the next consumer",
			Unit:        "1",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
	}, metricdatatest.IgnoreTimestamp(), metricdatatest.IgnoreValue())
	require.NoError(t, testTel.Shutdown(context.Background()))
}
