// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("traceduration")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/connector/tracedurationconnector"
)

const (
	TracesToMetricsStability = component.StabilityLevelAlpha
	TracesToLogsStability    = component.StabilityLevelAlpha
)
