# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: splunkhecexporter

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Set the default value of the idle connection timeout to 10s, rather than 30s by default

# One or more tracking issues related to the change
issues: [20543]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext:
