# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: breaking

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: spanmetricsconnector

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Remove deprecated `latency_histogram_buckets` configuration parameter.

# One or more tracking issues related to the change
issues: [19372]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  Use the `histogram` configuration section to provide buckets for
  explicit buckets histogram metrics. 
